"use client";

import Link from "next/link";
import { useEffect, useState, type DragEvent, type MouseEvent, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { ApprovedIconSprite, ApprovedTaskModal, type ScheduleItem, type ScheduleOption, type SchedulePriority } from "@/presentation/schedule/schedule-view";
import { TaskMetadata, TaskPriorityBadge, TaskRepeatMetadata } from "@/presentation/shared/task-metadata";
import { ActionToastStack, ConfirmDeleteDialog, useActionToasts } from "@/presentation/shared/action-feedback";

export type ProjectLocale="ko"|"en";
export type ProjectPreviewProject={id:string;title:{ko:string;en:string};color:string;count:number;area?:{id:string;title:{ko:string;en:string};color:string}};
export type ProjectPreviewTask={id:string;title:{ko:string;en:string};goalMinutes:number|null;focusedSeconds?:number;priority:SchedulePriority;repeat:"none"|"daily"|"weekly"|"monthly";scheduledDates:string[];schedule:{ko:string;en:string};completed?:boolean};
export type ProjectPreviewSection={id:string;title:{ko:string;en:string};tasks:ProjectPreviewTask[]};

function Icon({name}:{name:string}) {
  const inline:Record<string,ReactNode>={weather:<><circle cx="16.5" cy="7" r="5"/><path d="M3.5 20h11.8a3.7 3.7 0 0 0 .35-7.38A5.1 5.1 0 0 0 6 14.1 3.1 3.1 0 0 0 3.5 20Z"/></>};
  return <svg viewBox="0 0 24 24" aria-hidden="true">{inline[name]??<use href={`#i-${name}`}/>}</svg>;
}
const colors=["sky","mint","lilac","peach","butter","rose","coral","teal","navy","gray"];

export function ApprovedProjectsPresentation(props:{locale:ProjectLocale;onLocaleChange:()=>void;projects:ProjectPreviewProject[];initialSections:ProjectPreviewSection[];areas:ScheduleOption[];navigationBasePath?:string;onSignOut?:()=>void;onCreateTask?:(form:FormData)=>Promise<void>;onUpdateTask?:(form:FormData)=>Promise<void>;onArchiveTask?:(id:string)=>Promise<void>;onDeleteTask?:(id:string)=>Promise<void>;onCreateProject?:(name:string,color:string,areaId:string)=>Promise<void>;onUpdateProject?:(id:string,name:string,color:string,areaId:string)=>Promise<void>;onArchiveProject?:(id:string)=>Promise<void>;onDeleteProject?:(id:string)=>Promise<void>;onCreateSection?:(projectId:string,name:string)=>Promise<void>;onUpdateSection?:(id:string,name:string)=>Promise<void>;onDeleteSection?:(id:string)=>Promise<void>;onMoveTask?:(taskId:string,sectionId:string,targetIndex:number)=>Promise<void>;onMoveSection?:(projectId:string,sectionId:string,targetIndex:number)=>Promise<void>}) {
  const {locale}=props,router=useRouter();
  const [projectId,setProjectId]=useState(props.projects[0]?.id??"");
  const [collapsed,setCollapsed]=useState(false),[view,setView]=useState<"list"|"board">("list");
  const [sections,setSections]=useState(props.initialSections);
  const [modal,setModal]=useState<"project-new"|"project-edit"|"task"|"section-new"|"section-edit"|null>(null);
  const [editingTask,setEditingTask]=useState<ProjectPreviewTask|null>(null);
  const [menu,setMenu]=useState<string|null>(null),[menuPosition,setMenuPosition]=useState<{left:number;top:number}|null>(null);
  const [dragTask,setDragTask]=useState<{taskId:string;sectionId:string}|null>(null),[dragSection,setDragSection]=useState<string|null>(null);
  const [color,setColor]=useState("sky"),[areaOpen,setAreaOpen]=useState(false),[selectedArea,setSelectedArea]=useState("");
  const [deleteTarget,setDeleteTarget]=useState<{id:string;name:string;kind:"project"|"section"|"task"}|null>(null);
  const {toasts,notify}=useActionToasts();
  const project=props.projects.find(item=>item.id===projectId)??props.projects[0];
  const t=locale==="ko"?{
    schedule:"일정",tasks:"작업",areas:"영역",projects:"프로젝트",reports:"리포트",archive:"보관함",search:"검색",language:"한국어",logout:"로그아웃",
    eyebrow:"끝이 있는 목표",title:"프로젝트",help:"완료를 향해 움직이는 작업을 묶어서 관리해요.",addProject:"프로젝트 추가",progress:"진행률",next:"다음 일정",focus:"누적 집중",
    list:"목록",board:"보드",section:"섹션",task:"작업",today:"오늘 · 2개",edit:"수정",store:"보관",remove:"삭제",newProject:"새 프로젝트",
    projectHelp:"영역 없이도 프로젝트를 만들 수 있어요.",name:"이름",projectName:"프로젝트 이름",area:"영역",noArea:"영역 없음",color:"색상",cancel:"취소",create:"만들기",newSection:"새 섹션",sectionName:"섹션 이름",
  }:{
    schedule:"Schedule",tasks:"Tasks",areas:"Areas",projects:"Projects",reports:"Reports",archive:"Archive",search:"Search",language:"English",logout:"Log out",
    eyebrow:"PROJECTS",title:"Projects",help:"Group work that moves toward a clear outcome.",addProject:"Add project",progress:"Progress",next:"Next schedule",focus:"Total focus",
    list:"List",board:"Board",section:"Section",task:"Task",today:"Today · 2",edit:"Edit",store:"Archive",remove:"Delete",newProject:"New project",
    projectHelp:"A project can exist without an area.",name:"Name",projectName:"Project name",area:"Area",noArea:"No area",color:"Color",cancel:"Cancel",create:"Create",newSection:"New section",sectionName:"Section name",
  };
  const nav=[["calendar","schedule",t.schedule],["checklist","tasks",t.tasks],["grid","areas",t.areas],["folder","projects",t.projects],["chart","reports",t.reports],["archive","archive",t.archive]];
  const allTasks=sections.flatMap(section=>section.tasks);
  const completed=allTasks.filter(task=>task.completed).length,percent=allTasks.length?Math.round(completed/allTasks.length*100):0;
  const options:ScheduleOption[]=props.projects.map(item=>({id:item.id,title:item.title[locale],color:item.color,kind:"project" as const}));
  const asItem=(task:ProjectPreviewTask):ScheduleItem=>({id:task.id,taskId:task.id,title:task.title[locale],status:task.completed?"completed":"planned",projectTitle:project?.title[locale]??null,locationColor:project?.color??"gray",priority:task.priority,estimatedMinutes:task.goalMinutes,dailyGoalMinutes:task.goalMinutes,focusedSeconds:task.focusedSeconds??0,projectId:project?.id??null,areaId:null,repeat:task.repeat,scheduledDates:task.scheduledDates});
  useEffect(()=>{
    const key=(event:KeyboardEvent)=>{if(event.key==="Escape"){setModal(null);setEditingTask(null);setMenu(null);setAreaOpen(false);}};
    const outside=(event:PointerEvent)=>{const target=event.target as Element;if(!target.closest("[data-project-menu]"))setMenu(null);if(!target.closest("[data-area-select]"))setAreaOpen(false);};
    document.addEventListener("keydown",key);document.addEventListener("pointerdown",outside);return()=>{document.removeEventListener("keydown",key);document.removeEventListener("pointerdown",outside);};
  },[]);
  const openMenu=(event:MouseEvent<HTMLButtonElement>,key:string)=>{const rect=event.currentTarget.getBoundingClientRect();setMenuPosition({top:Math.min(window.innerHeight-140,rect.bottom+5),left:Math.max(8,rect.right-170)});setMenu(current=>current===key?null:key);};
  const base=props.navigationBasePath??"/ui-preview";
  const hrefFor=(path:string)=>!base&&path==="schedule"?"/":`${base}/${path}`.replace("//","/");
  const moveTask=(targetSectionId:string,targetTaskId?:string)=>{
    if(!dragTask)return;
    let moving:ProjectPreviewTask|undefined;
    const next=sections.map(section=>({...section,tasks:section.tasks.filter(task=>{if(task.id===dragTask.taskId){moving=task;return false;}return true;})}));
    if(moving){const target=next.find(section=>section.id===targetSectionId);if(target){const index=targetTaskId?target.tasks.findIndex(task=>task.id===targetTaskId):-1;target.tasks.splice(index<0?target.tasks.length:index,0,moving);}}
    setSections(next);void props.onMoveTask?.(dragTask.taskId,targetSectionId,targetTaskId?next.find(section=>section.id===targetSectionId)?.tasks.findIndex(task=>task.id===targetTaskId)??0:next.find(section=>section.id===targetSectionId)?.tasks.length??0);setDragTask(null);
  };
  const moveSection=(targetId:string)=>{if(!dragSection||dragSection===targetId)return setDragSection(null);const moving=dragSection;setSections(current=>{const source=current.find(section=>section.id===moving);if(!source)return current;const rest=current.filter(section=>section.id!==moving);const index=rest.findIndex(section=>section.id===targetId);rest.splice(index<0?rest.length:index,0,source);void props.onMoveSection?.(project?.id??"",moving,index<0?rest.length-1:index);return rest;});setDragSection(null);};
  return <><ApprovedIconSprite/><div className="app-shell"><aside className="sidebar">
    <Link className="brand" href={hrefFor("schedule")}><span className="brand-mark"><Icon name="weather"/></span><strong>Workday</strong></Link>
    <nav className="main-nav">{nav.map(([icon,path,label])=><button key={path} className={`nav-item ${path==="projects"?"is-active":""}`} type="button" onClick={()=>router.push(hrefFor(path))}><Icon name={icon}/><span>{label}</span></button>)}</nav>
    <button className="search" type="button" onClick={()=>router.push(`${base}/search`.replace("//","/"))}><Icon name="search"/><span>{t.search}</span></button><div className="sidebar-bottom"><button className="utility" type="button" onClick={props.onLocaleChange}><Icon name="globe"/><span>{t.language}</span></button><button className="utility" type="button" onClick={props.onSignOut}><Icon name="logout"/><span>{t.logout}</span></button></div>
  </aside><main className="content"><section className="page is-active">
    <header className="page-head"><div><span className="eyebrow">{t.eyebrow}</span><h1>{t.title}</h1><p>{t.help}</p></div><button className="button primary page-create-button" type="button" onClick={()=>{setColor("sky");setSelectedArea("");setModal("project-new");}}><Icon name="plus"/><span>{t.addProject}</span></button></header>
    <div className={`workspace ${collapsed?"is-collapsed":""}`}><aside className="rail"><div className="rail-tools"><button className="icon-button collapse-rail" type="button" onClick={()=>setCollapsed(value=>!value)}><Icon name={collapsed?"panel-expand":"panel-collapse"}/></button></div><nav>{props.projects.map(item=><button type="button" className={item.id===project?.id?"is-active":""} key={item.id} onClick={()=>setProjectId(item.id)}><span><i className={`dot ${item.color}`}/><b>{item.title[locale]}</b></span><small>{item.count}</small></button>)}</nav></aside>
      <div className="workspace-body"><header className="detail-head"><div><div className="detail-title"><i className={`dot ${project?.color??"gray"}`}/><h2>{project?.title[locale]}</h2></div>{project?.area&&<p className="area-label"><i className={`dot ${project.area.color}`}/><span>{project.area.title[locale]}</span></p>}</div><div data-project-menu><button className="icon-button menu-trigger" type="button" onClick={event=>openMenu(event,"project")}><Icon name="more"/></button>{menu==="project"&&<Menu locale={locale} position={menuPosition} onEdit={()=>{setColor(project?.color??"sky");setSelectedArea(project?.area?.id??"");setModal("project-edit");setMenu(null);}} onArchive={()=>{if(project)void props.onArchiveProject?.(project.id);notify("archive",project?.title[locale]??"");setMenu(null);}} onDelete={()=>{if(project)setDeleteTarget({id:project.id,name:project.title[locale],kind:"project"});setMenu(null);}}/>}</div></header>
      <div className="project-summary"><article><span>{t.progress}</span><strong>{percent}%</strong><div className="progress"><i style={{width:`${percent}%`}}/></div></article><article><span>{t.next}</span><strong>{t.today}</strong></article><article><span>{t.focus}</span><strong>{locale==="ko"?"8시간 25분":"8h 25m"}</strong></article></div>
      <div className="project-toolbar"><div className="view-switch"><button className={view==="list"?"is-active":""} type="button" onClick={()=>setView("list")}><Icon name="list"/><span>{t.list}</span></button><button className={view==="board"?"is-active":""} type="button" onClick={()=>setView("board")}><Icon name="board"/><span>{t.board}</span></button></div><div>{view==="board"&&<button className="button subtle" type="button" onClick={()=>setModal("section-new")}><Icon name="plus"/><span>{t.section}</span></button>}<button className="button subtle" type="button" onClick={()=>setModal("task")}><Icon name="plus"/><span>{t.task}</span></button></div></div>
      <div className={`project-list project-view ${view==="list"?"is-active":""}`}>{sections.map(section=><section key={section.id}><div className="section-title"><h3>{section.title[locale]}</h3><span>{section.tasks.length}</span></div><div className="directory-list sortable-list">{section.tasks.map(task=><article className="directory-row sortable-item" key={task.id} onDragOver={event=>event.preventDefault()} onDrop={()=>moveTask(section.id,task.id)}><span className="list-drag" draggable onDragStart={()=>setDragTask({taskId:task.id,sectionId:section.id})}><Icon name="grip"/></span><div><span className="task-title-line"><strong>{task.title[locale]}</strong><TaskPriorityBadge locale={locale} priority={task.priority}/></span><TaskMetadata locale={locale} goalMinutes={task.goalMinutes} trailing={task.repeat!=="none"?<TaskRepeatMetadata locale={locale} repeat={task.repeat}/>:undefined}/></div><div><button className="schedule-button" type="button" onClick={()=>setEditingTask(task)}><Icon name="calendar-days"/><span>{task.schedule[locale]}</span></button><div data-project-menu><button className="icon-button menu-trigger" type="button" onClick={event=>openMenu(event,task.id)}><Icon name="more"/></button>{menu===task.id&&<Menu locale={locale} position={menuPosition} onEdit={()=>{setEditingTask(task);setMenu(null);}} onArchive={()=>{setSections(current=>current.map(value=>({...value,tasks:value.tasks.filter(item=>item.id!==task.id)})));notify("archive",task.title[locale]);setMenu(null);}} onDelete={()=>{setDeleteTarget({id:task.id,name:task.title[locale],kind:"task"});setMenu(null);}}/>}</div></div></article>)}</div></section>)}</div>
      <div className={`board project-view ${view==="board"?"is-active":""}`} onDragOver={event=>event.preventDefault()}>{sections.map(section=><section className="board-column" key={section.id} onDragOver={event=>event.preventDefault()} onDrop={()=>dragTask?moveTask(section.id):moveSection(section.id)}><header><span className="drag" draggable onDragStart={()=>setDragSection(section.id)}><Icon name="grip"/></span><strong>{section.title[locale]}</strong><small>{section.tasks.length}</small><div data-project-menu><button className="icon-button menu-trigger" type="button" onClick={event=>openMenu(event,`section:${section.id}`)}><Icon name="more"/></button>{menu===`section:${section.id}`&&<Menu locale={locale} position={menuPosition} onEdit={()=>{setModal("section-edit");setMenu(null);}} onArchive={()=>{notify("archive",section.title[locale]);setMenu(null);}} onDelete={()=>{setDeleteTarget({id:section.id,name:section.title[locale],kind:"section"});setMenu(null);}}/>}</div></header>{section.tasks.map(task=><article className={`board-card ${task.completed?"is-complete":""}`} draggable key={task.id} onDragStart={event=>{event.stopPropagation();setDragTask({taskId:task.id,sectionId:section.id});}} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.stopPropagation();moveTask(section.id,task.id);}}><div><span className="drag"><Icon name="grip"/></span><span className="task-title-line"><strong>{task.title[locale]}</strong><TaskPriorityBadge locale={locale} priority={task.priority}/></span><div data-project-menu><button className="icon-button menu-trigger" type="button" onClick={event=>openMenu(event,`card:${task.id}`)}><Icon name="more"/></button>{menu===`card:${task.id}`&&<Menu locale={locale} position={menuPosition} onEdit={()=>{setEditingTask(task);setMenu(null);}} onArchive={()=>{setSections(current=>current.map(value=>({...value,tasks:value.tasks.filter(item=>item.id!==task.id)})));notify("archive",task.title[locale]);setMenu(null);}} onDelete={()=>{setDeleteTarget({id:task.id,name:task.title[locale],kind:"task"});setMenu(null);}}/>}</div></div><TaskMetadata locale={locale} goalMinutes={task.goalMinutes} trailing={task.repeat!=="none"?<TaskRepeatMetadata locale={locale} repeat={task.repeat}/>:undefined}/></article>)}</section>)}</div>
      </div></div>
  </section></main></div>
  {(modal==="task"||editingTask)&&<ApprovedTaskModal locale={locale} selectedKey={new Date().toISOString().slice(0,10)} todayKey={new Date().toISOString().slice(0,10)} defaultDates={[]} defaultLocation={project?`project:${project.id}`:""} options={options} sectionOptions={sections.filter(section=>section.id!=="default").map(section=>({id:section.id,title:section.title[locale]}))} defaultSectionId={editingTask?(()=>{const id=sections.find(section=>section.tasks.some(task=>task.id===editingTask.id))?.id;return id==="default"?"":id??"";})():""} initial={editingTask?asItem(editingTask):undefined} onClose={()=>{setModal(null);setEditingTask(null);}} onSubmit={editingTask?(props.onUpdateTask??(async()=>{})):(props.onCreateTask??(async()=>{}))}/>}
  {(modal==="project-new"||modal==="project-edit")&&<ProjectModal locale={locale} edit={modal==="project-edit"} initialName={modal==="project-edit"?project?.title[locale]??"":""} color={color} onColor={setColor} areas={props.areas} selectedArea={selectedArea} onArea={setSelectedArea} areaOpen={areaOpen} onAreaOpen={setAreaOpen} onClose={()=>setModal(null)} onSubmit={async(name,nextColor,areaId)=>{if(modal==="project-edit"&&project)await props.onUpdateProject?.(project.id,name,nextColor,areaId);else await props.onCreateProject?.(name,nextColor,areaId);setModal(null);}}/>}
  {(modal==="section-new"||modal==="section-edit")&&<NameModal locale={locale} title={modal==="section-edit"?(locale==="ko"?"섹션 수정":"Edit section"):t.newSection} label={t.sectionName} onClose={()=>setModal(null)} onSubmit={async name=>{if(modal==="section-edit"){const sectionId=menu?.replace("section:","")??sections[0]?.id;if(sectionId)await props.onUpdateSection?.(sectionId,name);}else if(project)await props.onCreateSection?.(project.id,name);setModal(null);}}/>}
  {deleteTarget&&<ConfirmDeleteDialog locale={locale} name={deleteTarget.name} onCancel={()=>setDeleteTarget(null)} onConfirm={()=>{if(deleteTarget.kind==="task"){void props.onDeleteTask?.(deleteTarget.id);setSections(current=>current.map(section=>({...section,tasks:section.tasks.filter(task=>task.id!==deleteTarget.id)})));}if(deleteTarget.kind==="section"){void props.onDeleteSection?.(deleteTarget.id);setSections(current=>current.filter(section=>section.id!==deleteTarget.id));}if(deleteTarget.kind==="project")void props.onDeleteProject?.(deleteTarget.id);notify("delete",deleteTarget.name);setDeleteTarget(null);}}/>}
  <ActionToastStack locale={locale} toasts={toasts}/>
  </>;
}

function Menu({locale,position,onEdit,onArchive,onDelete}:{locale:ProjectLocale;position:{left:number;top:number}|null;onEdit:()=>void;onArchive:()=>void;onDelete:()=>void}){return <div className="menu popover" style={position??undefined}><button type="button" onClick={onEdit}><Icon name="edit"/><span>{locale==="ko"?"수정":"Edit"}</span></button><button type="button" onClick={onArchive}><Icon name="archive"/><span>{locale==="ko"?"보관":"Archive"}</span></button><button className="danger" type="button" onClick={onDelete}><Icon name="trash"/><span>{locale==="ko"?"삭제":"Delete"}</span></button></div>;}
function ColorOptions({value,onChange}:{value:string;onChange:(value:string)=>void}){return <div className="color-options">{colors.map(color=><button type="button" aria-label={color} key={color} className={`${color} ${value===color?"is-active":""}`} onClick={()=>onChange(color)}><i/></button>)}</div>;}
function ProjectModal(props:{locale:ProjectLocale;edit:boolean;initialName:string;color:string;onColor:(value:string)=>void;areas:ScheduleOption[];selectedArea:string;onArea:(value:string)=>void;areaOpen:boolean;onAreaOpen:(value:boolean)=>void;onClose:()=>void;onSubmit:(name:string,color:string,areaId:string)=>Promise<void>}){const ko=props.locale==="ko";const selected=props.areas.find(area=>area.id===props.selectedArea),[name,setName]=useState(props.initialName);return <div className="modal-layer"><button className="modal-backdrop" onClick={props.onClose}/><section className="modal small-modal"><header><div><h2>{props.edit?(ko?"프로젝트 수정":"Edit project"):(ko?"새 프로젝트":"New project")}</h2><p>{ko?"영역 없이도 프로젝트를 만들 수 있어요.":"A project can exist without an area."}</p></div><button className="icon-button" type="button" onClick={props.onClose}><Icon name="x"/></button></header><div className="modal-body"><label className="field"><span>{ko?"이름":"Name"}</span><input autoFocus className="form-input" value={name} onChange={event=>setName(event.target.value)} placeholder={ko?"프로젝트 이름":"Project name"}/></label><label className="field" data-area-select><span>{ko?"영역":"Area"}</span><button className="select-trigger" type="button" onClick={()=>props.onAreaOpen(!props.areaOpen)}><span><i className={`dot ${selected?.color??"gray"}`}/><b>{selected?.title??(ko?"영역 없음":"No area")}</b></span><Icon name="chevron-down"/></button>{props.areaOpen&&<div className="select-menu" style={{zIndex:310}}><button type="button" onClick={()=>{props.onArea("");props.onAreaOpen(false);}}><i className="dot gray"/><span>{ko?"영역 없음":"No area"}</span></button>{props.areas.map(area=><button type="button" key={area.id} onClick={()=>{props.onArea(area.id);props.onAreaOpen(false);}}><i className={`dot ${area.color}`}/><span>{area.title}</span></button>)}</div>}</label><fieldset className="field"><legend>{ko?"색상":"Color"}</legend><ColorOptions value={props.color} onChange={props.onColor}/></fieldset></div><footer><button className="button subtle" type="button" onClick={props.onClose}>{ko?"취소":"Cancel"}</button><button className="button primary" type="button" disabled={!name.trim()} onClick={()=>void props.onSubmit(name.trim(),props.color,props.selectedArea)}>{props.edit?(ko?"저장":"Save"):(ko?"만들기":"Create")}</button></footer></section></div>;}
function NameModal({locale,title,label,onClose,onSubmit}:{locale:ProjectLocale;title:string;label:string;onClose:()=>void;onSubmit:(name:string)=>Promise<void>}){const [name,setName]=useState("");return <div className="modal-layer"><button className="modal-backdrop" onClick={onClose}/><section className="modal small-modal"><header><div><h2>{title}</h2></div><button className="icon-button" type="button" onClick={onClose}><Icon name="x"/></button></header><div className="modal-body"><label className="field"><span>{label}</span><input className="form-input" value={name} onChange={event=>setName(event.target.value)} autoFocus/></label></div><footer><button className="button subtle" type="button" onClick={onClose}>{locale==="ko"?"취소":"Cancel"}</button><button className="button primary" type="button" disabled={!name.trim()} onClick={()=>void onSubmit(name.trim())}>{locale==="ko"?"만들기":"Create"}</button></footer></section></div>;}
