import Link from "next/link";
import { AppNav } from "@/components/app-nav";
import { ConfirmSubmit, EditableText } from "@/components/editable-text";
import { archiveProject, archiveTask, createProject, createTask, deleteProject, deleteTask, moveTaskToProject, restoreProject, restoreTask, updateProject, updateTask } from "@/lib/actions";
import { getLocale } from "@/lib/i18n";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

export default async function ProjectsPage({ searchParams }: { searchParams: Promise<{ project?: string }> }) {
  const [{ project: projectId }, locale] = await Promise.all([searchParams, getLocale()]);
  const [projects, inboxCount, archivedProjects, archivedTasks] = await Promise.all([
    prisma.project.findMany({ where: { status: "active" }, orderBy: [{ sortOrder: "asc" }, { createdAt: "asc" }], include: { tasks: { where: { status: "active" }, orderBy: [{ sortOrder: "asc" }, { createdAt: "asc" }] } } }),
    prisma.task.count({ where: { projectId: null, status: "active" } }),
    prisma.project.findMany({ where: { status: "archived" }, orderBy: { archivedAt: "desc" }, include: { _count: { select: { tasks: true } } } }),
    prisma.task.findMany({ where: { status: "archived" }, orderBy: { archivedAt: "desc" }, include: { project: true } }),
  ]);
  const selected = projects.find(project => project.id === projectId) ?? projects[0] ?? null;
  return <main className="shell"><AppNav/>
    <header className="pageHeader"><div><p className="eyebrow">{locale === "ko" ? "장기 작업 공간" : "LONG-TERM WORK"}</p><h1>{locale === "ko" ? "프로젝트" : "Projects"}</h1><p className="lede">{locale === "ko" ? "관련 작업을 목적별로 모읍니다. 날짜별 실행 상태와 프로젝트 구조는 서로 독립적으로 유지됩니다." : "Organize related tasks by purpose. Project structure stays separate from daily execution."}</p></div><span className="status">{projects.length}{locale === "ko" ? "개" : ""}</span></header>
    <div className="projectsWorkspace">
      <aside className="panel projectRail"><div className="railHeading"><h2>{locale === "ko" ? "목록" : "Lists"}</h2></div><nav><Link className="inboxLink" href="/inbox"><span>{locale === "ko" ? "받은편지함" : "Inbox"}</span><small>{inboxCount}</small></Link>{projects.map(project => <Link className={project.id === selected?.id ? "active" : ""} href={`/projects?project=${project.id}`} key={project.id}><span>{project.title}</span><small>{project.tasks.length}</small></Link>)}</nav><details className="categoryCreate"><summary>{locale === "ko" ? "새 프로젝트" : "New project"}</summary><form action={createProject}><input name="title" placeholder={locale === "ko" ? "프로젝트 이름" : "Project name"} aria-label={locale === "ko" ? "프로젝트 이름" : "Project name"} required maxLength={120}/><button className="button full">{locale === "ko" ? "프로젝트 만들기" : "Create project"}</button></form></details></aside>
      <section className="panel projectTasks">{selected ? <><header className="taskWorkspaceHeader"><div><p className="workspaceLabel">{locale === "ko" ? "프로젝트 작업" : "PROJECT TASKS"}</p><EditableText action={updateProject} idName="projectId" id={selected.id} value={selected.title} label={locale === "ko" ? "프로젝트 이름 수정" : "Rename project"} className="categoryName"/><p>{locale === "ko" ? "칸반은 다음 릴리스에서 Section을 열로 사용해 추가됩니다." : "A later release will use Sections as Kanban columns."}</p></div><div className="libraryActions"><form action={archiveProject}><input type="hidden" name="projectId" value={selected.id}/><button className="textButton muted">{locale === "ko" ? "보관" : "Archive"}</button></form><ConfirmSubmit action={deleteProject} fields={{ projectId: selected.id }} message={locale === "ko" ? `‘${selected.title}’ 프로젝트를 삭제할까요? 작업은 받은편지함으로 이동합니다.` : `Delete “${selected.title}”? Its tasks will move to Inbox.`}><button className="textButton dangerText">{locale === "ko" ? "삭제" : "Delete"}</button></ConfirmSubmit></div></header>
        <div className="taskRows">{selected.tasks.map(task => <div className="libraryTask" key={task.id}><EditableText action={updateTask} idName="taskId" id={task.id} value={task.title} label={locale === "ko" ? "작업 이름 수정" : "Rename task"}/><div className="libraryActions"><form action={moveTaskToProject}><input type="hidden" name="taskId" value={task.id}/><input type="hidden" name="projectId" value=""/><button className="textButton accent">{locale === "ko" ? "받은편지함으로" : "To Inbox"}</button></form><form action={archiveTask}><input type="hidden" name="taskId" value={task.id}/><button className="textButton muted">{locale === "ko" ? "보관" : "Archive"}</button></form><ConfirmSubmit action={deleteTask} fields={{ taskId: task.id }} message={locale === "ko" ? `‘${task.title}’ 작업을 삭제할까요? 날짜별 스냅샷은 유지됩니다.` : `Delete “${task.title}”? Workday snapshots will remain.`}><button className="textButton dangerText">{locale === "ko" ? "삭제" : "Delete"}</button></ConfirmSubmit></div></div>)}</div>
        {!selected.tasks.length && <p className="empty">{locale === "ko" ? "이 프로젝트에 아직 작업이 없습니다." : "No tasks in this project yet."}</p>}
        <details className="addDetail"><summary>{locale === "ko" ? "프로젝트에 작업 추가" : "Add project task"}</summary><form action={createTask} className="rowForm detailCreate"><input type="hidden" name="projectId" value={selected.id}/><input name="title" placeholder={locale === "ko" ? "새 작업 이름" : "New task name"} aria-label={locale === "ko" ? "새 작업 이름" : "New task name"} required maxLength={120}/><button className="button secondary">{locale === "ko" ? "추가" : "Add"}</button></form></details>
      </> : <div className="emptyState"><p>{locale === "ko" ? "첫 프로젝트를 만들거나 받은편지함에 작업을 수집하세요." : "Create your first project or capture tasks in Inbox."}</p></div>}</section>
    </div>
    <details className="panel archiveBox"><summary>{locale === "ko" ? "보관함" : "Archive"} ({archivedProjects.length + archivedTasks.length})</summary><div className="archiveGroups"><section><h3>{locale === "ko" ? "보관된 프로젝트" : "Archived projects"}</h3>{archivedProjects.map(project => <div className="archiveRow" key={project.id}><span>{project.title}<small>{project._count.tasks}</small></span><div className="libraryActions"><form action={restoreProject}><input type="hidden" name="projectId" value={project.id}/><button className="textButton accent">{locale === "ko" ? "복원" : "Restore"}</button></form><ConfirmSubmit action={deleteProject} fields={{ projectId: project.id }} message={locale === "ko" ? `‘${project.title}’ 프로젝트를 삭제할까요?` : `Delete “${project.title}”?`}><button className="textButton dangerText">{locale === "ko" ? "삭제" : "Delete"}</button></ConfirmSubmit></div></div>)}</section><section><h3>{locale === "ko" ? "보관된 작업" : "Archived tasks"}</h3>{archivedTasks.map(task => <div className="archiveRow" key={task.id}><span>{task.title}<small>{task.project?.title ?? (locale === "ko" ? "받은편지함" : "Inbox")}</small></span><div className="libraryActions"><form action={restoreTask}><input type="hidden" name="taskId" value={task.id}/><button className="textButton accent">{locale === "ko" ? "복원" : "Restore"}</button></form><ConfirmSubmit action={deleteTask} fields={{ taskId: task.id }} message={locale === "ko" ? `‘${task.title}’ 작업을 삭제할까요?` : `Delete “${task.title}”?`}><button className="textButton dangerText">{locale === "ko" ? "삭제" : "Delete"}</button></ConfirmSubmit></div></div>)}</section></div></details>
  </main>;
}
