"use client";

import Link from "next/link";
import { useEffect, useState, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { ApprovedIconSprite } from "@/presentation/schedule/schedule-view";

export type ReportLocale="ko"|"en";
export type ReportDay={label:{ko:string;en:string};minutes:number;goalMinutes:number|null;planned:number;done?:number;areaSegments:number[];projectSegments:number[]};

function Icon({name}:{name:string}) {
  const inline:Record<string,ReactNode>={weather:<><circle cx="16.5" cy="7" r="5"/><path d="M3.5 20h11.8a3.7 3.7 0 0 0 .35-7.38A5.1 5.1 0 0 0 6 14.1 3.1 3.1 0 0 0 3.5 20Z"/></>};
  return <svg viewBox="0 0 24 24" aria-hidden="true">{inline[name]??<use href={`#i-${name}`}/>}</svg>;
}
const days:ReportDay[]=[
  {label:{ko:"월",en:"Mon"},minutes:75,goalMinutes:90,planned:3,areaSegments:[35,25,15],projectSegments:[30,25,20]},
  {label:{ko:"화",en:"Tue"},minutes:0,goalMinutes:60,planned:2,areaSegments:[],projectSegments:[]},
  {label:{ko:"수",en:"Wed"},minutes:150,goalMinutes:120,planned:4,areaSegments:[60,35,25,20,10],projectSegments:[65,40,30,15]},
  {label:{ko:"목",en:"Thu"},minutes:95,goalMinutes:null,planned:2,areaSegments:[45,30,20],projectSegments:[40,35,20]},
  {label:{ko:"금",en:"Fri"},minutes:120,goalMinutes:150,planned:4,areaSegments:[60,35,25],projectSegments:[50,40,30]},
  {label:{ko:"토",en:"Sat"},minutes:55,goalMinutes:60,planned:2,areaSegments:[30,25],projectSegments:[35,20]},
  {label:{ko:"일",en:"Sun"},minutes:0,goalMinutes:null,planned:0,areaSegments:[],projectSegments:[]},
];
const recorded=new Set([2,5,8,11,14,17,20,24,27,30]);
const plannedOnly=new Set([3,7,15,22,29]);
function duration(minutes:number,locale:ReportLocale){const h=Math.floor(minutes/60),m=minutes%60;return locale==="ko"?[h?`${h}시간`:"",m?`${m}분`:""].filter(Boolean).join(" ")||"0분":[h?`${h}h`:"",m?`${m}m`:""].filter(Boolean).join(" ")||"0m";}

export function ApprovedReportsPresentation({locale,onLocaleChange,navigationBasePath="/ui-preview",onSignOut,data,onSaveGoal}:{locale:ReportLocale;onLocaleChange:()=>void;navigationBasePath?:string;onSignOut?:()=>void;data?:{goalHours:number;actualMinutes:number;plannedMinutes:number;completed:number;sessions:number;activeDays:number;streak:number;days:ReportDay[]};onSaveGoal?:(hours:number)=>Promise<void>}) {
  const router=useRouter(),[period,setPeriod]=useState<"week"|"month">("week"),[offset,setOffset]=useState(0);
  const [selectedDay,setSelectedDay]=useState(2),[selectedDate,setSelectedDate]=useState(24),[goalOpen,setGoalOpen]=useState(false),[goal,setGoal]=useState(data?.goalHours??10),[sortLarge,setSortLarge]=useState(true);
  const t=locale==="ko"?{
    schedule:"일정",tasks:"작업",areas:"영역",projects:"프로젝트",reports:"리포트",archive:"보관함",search:"검색",language:"한국어",logout:"로그아웃",
    eyebrow:"실행 기록",title:"리포트",help:"계획과 실제 집중의 흐름을 함께 살펴봐요.",weekly:"주간",monthly:"월간",goal:"이번 주 집중 목표",editGoal:"목표 수정",
    focusGoal:"주간 집중 목표",planned:"계획한 집중 시간",actual:"실제 집중 시간",completed:"완료 작업",sessions:"집중 세션",active:"활동일",streak:"연속 집중",
    flow:"날짜별 집중 흐름",stacked:"영역별 누적",noRecord:"이날 진행한 집중 기록이 없어요",plannedNoFocus:"계획한 작업이 있지만 집중 기록은 없어요",noPlan:"이날은 계획한 작업이 없어요",chooseDay:"다른 요일을 선택하면 기록을 확인할 수 있어요.",
    byArea:"이번 주 영역별 집중",byProject:"이번 주 프로젝트별 집중",monthRecord:"7월 집중 기록",recorded:"기록 있음",weeklyGoals:"주별 집중 목표",
    taskDiff:"작업별 계획 · 실제 집중",large:"차이 큰 순",small:"차이 작은 순",completion:"요일별 계획 · 완료",cancel:"취소",save:"저장",
  }:{
    schedule:"Schedule",tasks:"Tasks",areas:"Areas",projects:"Projects",reports:"Reports",archive:"Archive",search:"Search",language:"English",logout:"Log out",
    eyebrow:"REPORTS",title:"Reports",help:"Compare your plans with actual focus.",weekly:"Weekly",monthly:"Monthly",goal:"This week's focus goal",editGoal:"Edit goal",
    focusGoal:"Weekly focus goal",planned:"Planned focus",actual:"Actual focus",completed:"Completed tasks",sessions:"Focus sessions",active:"Active days",streak:"Focus streak",
    flow:"Focus flow by date",stacked:"Stacked by area",noRecord:"No focus was recorded on this day",plannedNoFocus:"Tasks were planned, but no focus was recorded",noPlan:"No tasks were planned for this day",chooseDay:"Choose another day to view its focus record.",
    byArea:"This week by area",byProject:"This week by project",monthRecord:"July focus record",recorded:"Recorded",weeklyGoals:"Weekly focus goals",
    taskDiff:"Task plan · actual focus",large:"Largest difference",small:"Smallest difference",completion:"Planned · completed by day",cancel:"Cancel",save:"Save",
  };
  const nav=[["calendar","schedule",t.schedule],["checklist","tasks",t.tasks],["grid","areas",t.areas],["folder","projects",t.projects],["chart","reports",t.reports],["archive","archive",t.archive]];
  const hrefFor=(path:string)=>!navigationBasePath&&path==="schedule"?"/":`${navigationBasePath}/${path}`.replace("//","/");
  const reportDays=data?.days??days,actualHours=(data?.actualMinutes??525)/60,goalPercent=goal?Math.min(100,Math.round(actualHours/goal*100)):0,remainingHours=Math.max(0,goal-actualHours);
  const remainingLabel=remainingHours===0?(locale==="ko"?"목표 달성":"Goal reached"):(locale==="ko"?`${Math.floor(remainingHours)}시간 ${Math.round(remainingHours%1*60)}분 남음`:`${Math.floor(remainingHours)}h ${Math.round(remainingHours%1*60)}m remaining`);
  const goalIcon=goalPercent===0?"rain":goalPercent<40?"cloud":goalPercent<70?"cloud-sun":goalPercent<100?"partly-sunny":"sun";
  const periodLabel=period==="week"?(offset===0?(locale==="ko"?"7월 27일 – 8월 2일":"Jul 27 – Aug 2"):(locale==="ko"?"7월 20일 – 26일":"Jul 20 – 26")):(offset===0?(locale==="ko"?"2026년 7월":"July 2026"):(locale==="ko"?"2026년 6월":"June 2026"));
  useEffect(()=>{const escape=(event:KeyboardEvent)=>{if(event.key==="Escape")setGoalOpen(false);};document.addEventListener("keydown",escape);return()=>document.removeEventListener("keydown",escape);},[]);
  return <><ApprovedIconSprite/><div className="app-shell"><aside className="sidebar">
    <Link className="brand" href={hrefFor("schedule")}><span className="brand-mark"><Icon name="weather"/></span><strong>Workday</strong></Link>
    <nav className="main-nav">{nav.map(([icon,path,label])=><button key={path} className={`nav-item ${path==="reports"?"is-active":""}`} type="button" onClick={()=>router.push(hrefFor(path))}><Icon name={icon}/><span>{label}</span></button>)}</nav>
    <button className="search" type="button" onClick={()=>router.push(`${navigationBasePath}/search`.replace("//","/"))}><Icon name="search"/><span>{t.search}</span></button><div className="sidebar-bottom"><button className="utility" type="button" onClick={onLocaleChange}><Icon name="globe"/><span>{t.language}</span></button><button className="utility" type="button" onClick={onSignOut}><Icon name="logout"/><span>{t.logout}</span></button></div>
  </aside><main className="content"><section className="page is-active">
    <header className="page-head"><div><span className="eyebrow">{t.eyebrow}</span><h1>{t.title}</h1><p>{t.help}</p></div></header>
    <div className="report-toolbar"><div className="tabs report-period"><button className={period==="week"?"is-active":""} type="button" onClick={()=>setPeriod("week")}>{t.weekly}</button><button className={period==="month"?"is-active":""} type="button" onClick={()=>setPeriod("month")}>{t.monthly}</button></div><div className="period-nav"><button className="icon-button" type="button" onClick={()=>setOffset(value=>value-1)}><Icon name="chevron-left"/></button><strong>{periodLabel}</strong><button className="icon-button" type="button" onClick={()=>setOffset(value=>value+1)}><Icon name="chevron-right"/></button></div></div>
    {period==="week"&&<section className="weekly-goal-setting"><div className="weekly-goal-overview"><div><span className={`goal-cloud goal-state-${goalIcon}`}><Icon name={goalIcon}/></span><p className="goal-inline-copy"><strong>{t.goal}</strong><small><b>{locale==="ko"?`8시간 45분 / ${goal}시간`:`8h 45m / ${goal}h`}</b><i aria-hidden="true">·</i><span>{remainingLabel}</span></small></p></div><strong className="goal-panel-percent">{goalPercent}%</strong><button className="weekly-goal-edit" type="button" onClick={()=>setGoalOpen(true)}><Icon name="edit"/><span>{t.editGoal}</span></button></div><div className="weekly-goal-track"><i style={{width:`${goalPercent}%`}}/></div></section>}
    <div className="report-summary"><article><span>{period==="week"?t.focusGoal:(locale==="ko"?"월간 집중 합계":"Monthly focus total")}</span><strong>{period==="week"?`${goal}${locale==="ko"?"시간":"h"}`:(locale==="ko"?"31시간 20분":"31h 20m")}</strong><small>{period==="week"?(locale==="ko"?`목표의 ${goalPercent}% 달성`:`${goalPercent}% of goal`):(locale==="ko"?"이번 달 실제 집중":"Actual focus this month")}</small><i className="sky"/></article><article><span>{t.planned}</span><strong>{period==="week"?duration(data?.plannedMinutes??570,locale):(locale==="ko"?"34시간 10분":"34h 10m")}</strong><small>{locale==="ko"?"작업별 목표 시간 합계":"Sum of task goal times"}</small><i className="butter"/></article><article><span>{t.actual}</span><strong>{period==="week"?duration(data?.actualMinutes??525,locale):(locale==="ko"?"31시간 20분":"31h 20m")}</strong><small>{locale==="ko"?"계획 대비 실제 집중":"Actual against plan"}</small><i className="mint"/></article></div>
    <div className="metric-row"><article><span>{t.completed}</span><strong>{period==="week"?(data?.completed??18):67}</strong></article><article><span>{t.sessions}</span><strong>{period==="week"?(data?.sessions??24):86}</strong></article><article><span>{t.active}</span><strong>{period==="week"?(data?.activeDays??6):23}</strong></article><article><span>{t.streak}</span><strong>{data?.streak??4}{locale==="ko"?"일":" days"}</strong></article></div>
    {period==="week"?<WeeklyReport locale={locale} t={t} selected={selectedDay} onSelect={setSelectedDay} reportDays={reportDays}/>:<MonthlyReport locale={locale} t={t} selected={selectedDate} onSelect={setSelectedDate}/>}
    <div className="report-lower shared-report-bottom"><section className="report-card task-difference-card"><header className="section-title"><h2>{t.taskDiff}</h2><span><b className="sort-label">{sortLarge?t.large:t.small}</b><button className="icon-button sort-button" type="button" onClick={()=>setSortLarge(value=>!value)}><Icon name={sortLarge?"sort-large":"sort-small"}/></button></span></header><div className="ranking">{(sortLarge?[["리포트 차트 정리","1시간 30분 · 2시간 5분"],["포트폴리오 문구","1시간 · 45분"]]:[["포트폴리오 문구","1시간 · 45분"],["리포트 차트 정리","1시간 30분 · 2시간 5분"]]).map(([name,value])=><p key={name}><span>{name}</span><strong>{value}</strong></p>)}</div></section><Completion locale={locale} title={t.completion}/></div>
  </section></main></div>
  {goalOpen&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setGoalOpen(false)}/><section className="modal small-modal"><header><div><h2>{t.editGoal}</h2><p>{locale==="ko"?"이번 주에 집중할 목표 시간을 설정해요.":"Set your focus goal for this week."}</p></div><button className="icon-button" type="button" onClick={()=>setGoalOpen(false)}><Icon name="x"/></button></header><div className="modal-body"><label className="field weekly-goal-modal-field"><span>{locale==="ko"?"목표 시간":"Goal time"}</span><span className="weekly-goal-input"><input type="number" min=".5" max="168" step=".5" value={goal} onChange={event=>setGoal(Number(event.target.value))}/><b>{locale==="ko"?"시간":"h"}</b></span><small>{locale==="ko"?"0.5시간 단위로 최대 168시간까지 설정할 수 있어요.":"Set up to 168 hours in 0.5-hour steps."}</small></label></div><footer><button className="button subtle" type="button" onClick={()=>setGoalOpen(false)}>{t.cancel}</button><button className="button primary" type="button" onClick={()=>{void onSaveGoal?.(goal);setGoalOpen(false);}}>{t.save}</button></footer></section></div>}
  </>;
}

function WeeklyReport({locale,t,selected,onSelect,reportDays}:{locale:ReportLocale;t:Record<string,string>;selected:number;onSelect:(value:number)=>void;reportDays:ReportDay[]}){const day=reportDays[selected]??reportDays[0],[group,setGroup]=useState<"area"|"project">("area");const maxMinutes=Math.max(...reportDays.flatMap(item=>[item.minutes,item.goalMinutes??0]),1);return <><section className="report-card weekly-report"><header className="section-title"><h2>{t.flow}</h2></header><div className="weekly-chart"><div className="plot-grid">{reportDays.map((item,index)=>{const segments=group==="area"?item.areaSegments:item.projectSegments;const achievement=item.goalMinutes?Math.round(item.minutes/item.goalMinutes*100):null;return <button className={`chart-day ${selected===index?"is-selected":""}`} type="button" key={item.label.en} onClick={()=>onSelect(index)}><span className="bar-track">{item.goalMinutes!=null&&<i className="plan-bar" style={{height:`${Math.max(4,item.goalMinutes/maxMinutes*125)}px`}}/>}<span className="stack actual-stack" style={{height:`${item.minutes?Math.max(4,item.minutes/maxMinutes*125):0}px`}}>{segments.map((value,segment)=><i key={segment} className={(group==="area"?["sky","mint","peach","lilac","gray"]:["mint","sky","lilac","gray"])[segment]??"gray"} style={{height:`${item.minutes?value/item.minutes*100:0}%`}}/>)}</span><span className="bar-tooltip">{locale==="ko"?`계획 ${item.goalMinutes==null?"없음":duration(item.goalMinutes,locale)} · 실제 ${duration(item.minutes,locale)}${achievement==null?"":` · 달성 ${achievement}%`}`:`Plan ${item.goalMinutes==null?"none":duration(item.goalMinutes,locale)} · Actual ${duration(item.minutes,locale)}${achievement==null?"":` · ${achievement}%`}`}</span></span></button>})}</div><div className="weekday-grid">{reportDays.map(item=><strong key={item.label.en}>{item.label[locale]}</strong>)}</div><div className="duration-grid">{reportDays.map(item=><small key={item.label.en}>{duration(item.minutes,locale)}</small>)}</div></div>{day?.minutes?<ChartDetail locale={locale} title={`${day.label[locale]} · ${group==="area"?(locale==="ko"?"영역별 집중":"focus by area"):(locale==="ko"?"프로젝트별 집중":"focus by project")}`} group={group} onGroupChange={setGroup}/>:<Empty locale={locale} icon={day?.planned?"rain":"moon"} text={day?.planned?t.plannedNoFocus:t.noPlan} help={t.chooseDay}/>}</section><Rankings locale={locale} areaTitle={t.byArea} projectTitle={t.byProject}/></>;}
function MonthlyReport({locale,t,selected,onSelect}:{locale:ReportLocale;t:Record<string,string>;selected:number;onSelect:(value:number)=>void}){const has=recorded.has(selected),planned=plannedOnly.has(selected),[group,setGroup]=useState<"area"|"project">("area");return <><section className="monthly-report"><div className="month-layout"><section className="report-card month-calendar-section"><header className="section-title"><h2>{t.monthRecord}</h2><span className="month-record-legends"><b><i className="dot sky"/>{t.recorded}</b><b><i className="planned-only-dot"/>{locale==="ko"?"계획 있음":"Planned"}</b></span></header><div className="month-grid">{(locale==="ko"?["일","월","화","수","목","금","토"]:["S","M","T","W","T","F","S"]).map((value,index)=><span key={`${value}-${index}`}>{value}</span>)}{[1,2,3].map(value=><span key={`blank-${value}`}/>)}{Array.from({length:31},(_,index)=>index+1).map(value=><button type="button" key={value} className={`${value===selected?"is-selected":""} ${value===30?"is-today":""} ${recorded.has(value)?"is-recorded":""} ${plannedOnly.has(value)?"is-planned-only":""}`} onClick={()=>onSelect(value)}>{value}</button>)}</div></section><section className="report-card month-detail"><header className="section-title"><h2>{locale==="ko"?`7월 ${selected}일${has?" · 1시간 40분":""}`:`July ${selected}${has?" · 1h 40m":""}`}</h2></header>{has?<ChartDetail locale={locale} title="" group={group} onGroupChange={setGroup}/>:<Empty locale={locale} icon={planned?"rain":"moon"} text={planned?t.plannedNoFocus:t.noPlan} help={locale==="ko"?"다른 날짜를 선택하면 기록을 확인할 수 있어요.":"Choose another date to view its focus record."}/>}</section></div><div className="report-lower monthly-rankings"><Ranking locale={locale} title={locale==="ko"?"7월 영역별 집중":"July focus by area"}/><section className="report-card"><header className="section-title"><h2>{t.weeklyGoals}</h2><span>{locale==="ko"?"월간 목표로 합산하지 않음":"Not combined as a monthly goal"}</span></header><div className="weekly-goals">{[["6월 29일–7월 5일","6시간 10분 / 8시간"],["7월 6일–12일","7시간 40분 / 9시간"],["7월 13일–19일","8시간 45분 / 10시간"]].map(row=><p key={row[0]}><span>{row[0]}</span><strong>{row[1]}</strong></p>)}</div></section></div></section></>;}
function ChartDetail({locale,title,group="area",onGroupChange}:{locale:ReportLocale;title:string;group?:"area"|"project";onGroupChange?:(group:"area"|"project")=>void}){const rows=group==="area"?[["sky",locale==="ko"?"성장":"Growth","1h 20m"],["mint",locale==="ko"?"건강":"Health","45m"],["peach",locale==="ko"?"생활":"Life","25m"]]:[["mint","Workday","1h 05m"],["sky",locale==="ko"?"10km 달리기":"Run 10km","55m"],["gray",locale==="ko"?"프로젝트 없음":"No project","30m"]];return <div className="chart-detail"><div className={`donut ${group==="project"?"project-pie":""}`}><span className="pie-tooltip">{group==="area"?(locale==="ko"?"건강 · 45분 · 27%":"Health · 45m · 27%"):(locale==="ko"?"Workday · 1시간 5분 · 43%":"Workday · 1h 05m · 43%")}</span></div><div><div className="chart-detail-heading">{title&&<h3>{title}</h3>}{onGroupChange&&<div className="tabs chart-group-switch"><button className={group==="area"?"is-active":""} type="button" onClick={()=>onGroupChange("area")}>{locale==="ko"?"영역별":"By area"}</button><button className={group==="project"?"is-active":""} type="button" onClick={()=>onGroupChange("project")}>{locale==="ko"?"프로젝트별":"By project"}</button></div>}</div><p>{rows.map(row=><span key={row[1]}><i className={`dot ${row[0]}`}/><b>{row[1]}</b><strong>{row[2]}</strong></span>)}</p></div></div>;}
function Empty({locale,text,help,icon="cloud"}:{locale:ReportLocale;text:string;help:string;icon?:string}){return <div className="weekly-detail-empty"><span><Icon name={icon}/></span><strong>{text}</strong><small>{help}</small></div>;}
function Rankings({locale,areaTitle,projectTitle}:{locale:ReportLocale;areaTitle:string;projectTitle:string}){return <div className="report-lower weekly-rankings"><Ranking locale={locale} title={areaTitle}/><Ranking locale={locale} title={projectTitle} project/></div>;}
function Ranking({locale,title,project=false}:{locale:ReportLocale;title:string;project?:boolean}){const rows=project?[["mint","Workday","3h 05m"],["sky",locale==="ko"?"10km 달리기 준비":"10K preparation","2h 10m"],["gray",locale==="ko"?"프로젝트 없음":"No project","2h"]]:[["sky",locale==="ko"?"업무":"Work","3h 20m"],["mint",locale==="ko"?"건강":"Health","2h 35m"],["lilac",locale==="ko"?"개인 성장":"Personal growth","1h 50m"]];return <section className="report-card"><header className="section-title"><h2>{title}</h2><span>{locale==="ko"?"8시간 45분":"8h 45m"}</span></header><div className="ranking">{rows.map(row=><p key={row[1]}><span><i className={`dot ${row[0]}`}/><b>{row[1]}</b></span><strong>{row[2]}</strong></p>)}</div></section>;}
function Completion({locale,title}:{locale:ReportLocale;title:string}){return <section className="report-card"><header className="section-title"><h2>{title}</h2><span>{locale==="ko"?"계획 23 · 완료 18":"Planned 23 · completed 18"}</span></header><div className="completion-chart">{[["월",4,3],["화",3,3],["수",5,4],["목",2,1],["금",4,3],["토",3,2],["일",2,2]].map(([label,planned,done])=><div className="completion-row" key={String(label)}><span>{locale==="ko"?label:["Mon","Tue","Wed","Thu","Fri","Sat","Sun"][["월","화","수","목","금","토","일"].indexOf(String(label))]}</span><span className="completion-track"><i className="completion-fill" style={{width:`${Number(done)/Number(planned)*100}%`}}/></span><strong>{done}/{planned}</strong></div>)}</div></section>;}
